<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pembayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	function get_by_id2013($id)
    {
        $this->db->where('id_peserta', $id);
        $this->db->where('tahun_pembayaran', '2013');
        return $this->db->get($this->table)->result();
    }
	
	function get_by_id2014($id)
    {
        $this->db->where('id_peserta', $id);
        $this->db->where('tahun_pembayaran', '2014');
        return $this->db->get($this->table)->result();
    }
	
	function get_by_id2015($id)
    {
        $this->db->where('id_peserta', $id);
        $this->db->where('tahun_pembayaran', '2015');
        return $this->db->get($this->table)->result();
    }
	
	function get_by_id2016($id)
    {
        $this->db->where('id_peserta', $id);
        $this->db->where('tahun_pembayaran', '2016');
        return $this->db->get($this->table)->result();
    }
	
	function get_by_id2017($id)
    {
        $this->db->where('id_peserta', $id);
        $this->db->where('tahun_pembayaran', '2017');
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pembayaran', $q);
	$this->db->or_like('id_peserta', $q);
	$this->db->or_like('tahun_pembayaran', $q);
	$this->db->or_like('iuran_anggota', $q);
	$this->db->or_like('uang_pangkal', $q);
	$this->db->or_like('cetak_kta', $q);
	$this->db->or_like('icn', $q);
	$this->db->or_like('rekomendasi', $q);
	$this->db->or_like('kontribusi_gedung', $q);
	$this->db->or_like('status_transfer_dpw', $q);
	$this->db->or_like('status_transfer_dpp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pembayaran', $q);
	$this->db->or_like('id_peserta', $q);
	$this->db->or_like('tahun_pembayaran', $q);
	$this->db->or_like('iuran_anggota', $q);
	$this->db->or_like('uang_pangkal', $q);
	$this->db->or_like('cetak_kta', $q);
	$this->db->or_like('icn', $q);
	$this->db->or_like('rekomendasi', $q);
	$this->db->or_like('kontribusi_gedung', $q);
	$this->db->or_like('status_transfer_dpw', $q);
	$this->db->or_like('status_transfer_dpp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-09 08:28:19 */
/* http://harviacode.com */