<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Peserta_model extends CI_Model
{

    public $table = 'peserta';
    public $id = 'id_peserta';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function json() {
        $this->datatables->select('id_peserta,nama_peserta,no_ktp,no_anggota,tanggal_terdaftar,komisariat');
        $this->datatables->from('peserta');
        //add this line for join
        //$this->datatables->join('table2', 'records.field = table2.field');
        //$this->datatables->add_column('action', anchor(site_url('records/read/$1'),'Read')." | ".anchor(site_url('records/update/$1'),'Update')." | ".anchor(site_url('records/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_records');
        $this->datatables->add_column(
            'action', 
            '<div class="dropdown">
            <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown">Pilihan
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
            <li><a href="peserta/detail_pembayaran/$1" title="detail">Detail Pembayaran</a></li>
            <li><a href="peserta/pembayaran/$1" title="detail">Pembayaran</a></li>
            <li><a href="peserta/read/$1" title="detail">Detail Peserta</a></li>
            <li><a href="peserta/update/$1" title="detail">Edit Peserta</a></li>
            <li class="divider"></li>
            <li><a href="peserta/delete/$1" title="delete" onclick="javasciprt: return confirm("Apakah anda yakin ?")">Hapus Peserta</a></li>
            </ul>
            </div>',
            'id_peserta'
        );
        $this->db->order_by($this->id, 'DESC');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	function get_by_id_join($id)
    {
        $this->db->where('peserta.id_peserta', $id);
        $this->db->join('pembayaran', 'pembayaran.id_peserta = peserta.id_peserta');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_peserta', $q);
	$this->db->or_like('nama_peserta', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_anggota', $q);
	$this->db->or_like('tanggal_terdaftar', $q);
	$this->db->or_like('komisariat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_peserta', $q);
	$this->db->or_like('nama_peserta', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_anggota', $q);
	$this->db->or_like('tanggal_terdaftar', $q);
	$this->db->or_like('komisariat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Peserta_model.php */
/* Location: ./application/models/Peserta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-09 08:28:10 */
/* http://harviacode.com */